import { Button, DatePicker, Select } from "antd";
import Head from "next/head";
import Image from "next/image";
import CButton from "../components/Button";
import CHeader from "../components/Header";
import styles from "../styles/Home.module.scss";

const { Option } = Select;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ComEbenezer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-colorida.svg" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div style={{ width: "100%", height: "100vh" }}>
          <CHeader texto="Bem Vindo" />
        </div>
        <Image
          src="/logo-colorida.svg"
          alt="Ebenezer Logo"
          width={150}
          height={150}
        />
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <CButton tipo={undefined} texto="Vamos lá" />

        <div className="my-select-container">
          <Select
            style={{
              width: "98%",
              borderRadius: "15px",
            }}
            showSearch
            placeholder="Selecione o Tipo de Visita"
            onSelect={(e: any) => {
              // handleSelect(e);
            }}
          >
            <Option key="lol" value="lol">
              VIRTUAL
            </Option>
            <Option key="lol" value="lol">
              PRESENCIAL
            </Option>
          </Select>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/logo-texto-colorida.svg"
              alt="Ebenezer Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
